// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	UserName  string    `json:"user_name"`
	Balance   string    `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

type PaymentBy struct {
	ID          int64  `json:"id"`
	PaymentName string `json:"payment_name"`
}

type Transaction struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	PaymentID int64     `json:"payment_id"`
	CreatedAt time.Time `json:"created_at"`
	Desc      string    `json:"desc"`
	Amount    int64     `json:"amount"`
}
