// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreatePaymentName(ctx context.Context, paymentName string) (PaymentBy, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeletePaymenBy(ctx context.Context, id int64) error
	DeleteTransactionById(ctx context.Context, id int64) error
	GetAccountById(ctx context.Context, id int64) (Account, error)
	GetPaymentBy(ctx context.Context, arg GetPaymentByParams) ([]PaymentBy, error)
	GetPaymentById(ctx context.Context, id int64) (PaymentBy, error)
	GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]Transaction, error)
	// -- name: GetTransactionsByUserId :many
	// SELECT * FROM transactions WHERE account_id = $1;
	GetTransactionsById(ctx context.Context, id int64) (Transaction, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdatePaymentNameById(ctx context.Context, arg UpdatePaymentNameByIdParams) (PaymentBy, error)
	UpdateTransactionById(ctx context.Context, arg UpdateTransactionByIdParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
